---
################################################################################
#
#   CONSENSUS PROPERTIES
#
#   - List all algorithm-specific properties here.
#   - Nest keys where appropriate, and sort alphabetically for easier parsing.
#
################################################################################

# Consensus plugin package name goes here
name: obcpbft

# Maximum number of validators we expect in the network
N: 4
