vp0:
  extends:
    file: compose-defaults.yml
    service: vp
  environment:
    - OPENCHAIN_PEER_ID=vp0
    - OPENCHAIN_PEER_VALIDATOR_CONSENSUS=obcpbft
    - OPENCHAIN_PEER_VALIDATOR_REPLICAS_IPS=vp0:30303 vp1:30303 vp2:30303 vp3:30303
    - OPENCHAIN_SECURITY_ENROLLID=donq
    - OPENCHAIN_SCURITY_ENROLLSECRET=7avZQLwcUe9q

vp1:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp1
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - OPENCHAIN_SECURITY_ENROLLID=nepumuk
    - OPENCHAIN_SCURITY_ENROLLSECRET=9gvZQRwhUq9q
  links:
    - vp0

vp2:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp2
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - OPENCHAIN_SECURITY_ENROLLID=jim
    - OPENCHAIN_SCURITY_ENROLLSECRET=AwbeJH2kw9qK
  links:
    - vp0

vp3:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp3
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - OPENCHAIN_SECURITY_ENROLLID=lukas
    - OPENCHAIN_SCURITY_ENROLLSECRET=NPKYL39uKbkj
  links:
    - vp0
