---
################################################################################
#
#   PBFT PROPERTIES
#
#   - List all algorithm-specific properties here.
#   - Nest keys where appropriate, and sort alphabetically for easier parsing.
#
################################################################################
general:

    # Algorithm/plugin name goes here. Set it to the package name.
    name: pbft

    # How many Byzantine nodes can we tolerate?
    f: 1

    # Checkpoint period.
    K: 128

    # Timeouts
    timeout:

        # How long may a request take between reception and execution
        request: 2s

        # How long may a view change take
        viewchange: 2s


################################################################################
#
#   SECTION: REPLICA
#
#   - This applies to all validating peers.
#
################################################################################
replica:

    # The ID of the peer. Should be a non-negative integer.
    # The value set here is only read when running in testing mode.
    id: 0

...
